# https://www.nginx.com/blog/deploying-nginx-nginx-plus-docker/
# FROM nginx
# FROM nginx:stable-alpine
# RUN rm /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./default.conf /etc/nginx/conf.d/
# VOLUME /var/log/nginx/log
# CMD [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ]