ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}@sha256:8561e04d529fc9dd6a18ad67025d98553a01957d2ee1d3b28c0c5790ebfd5dbc
# COPY --chown=elasticsearch:elasticsearch ./assets/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/