ARG STACK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
# COPY --chown=elasticsearch:elasticsearch ./assets/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/